ci: clone node v2

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -30,6 +30,84 @@ jobs:
       - name: Clone Node V2 (avoid submodules)
         run: |
           git clone -b v2.0.0-alpha.1 --depth 1 --recurse-submodules https://github.com/cartesi/rollups-node.git
+      
+      - name: Wait for PostgreSQL to be ready
+        run: |
+          for i in {1..30}; do
+            if pg_isready -h localhost -p 5432 -U postgres; then
+              echo "PostgreSQL is ready";
+              exit 0;
+            fi;
+            sleep 2;
+          done;
+          echo "PostgreSQL did not become ready in time";
+          exit 1;
+
+      - name: Migrate Node V2 DB
+        run: |
+          cd rollups-node
+          eval $(make env)
+          make migrate
+
+      - name: Deps and Cartesi Machine
+        run: |
+          export CARTESI_MACHINE_VERSION=0.18.1
+          sudo apt-get update
+          sudo apt-get install -y libboost-all-dev lua5.4 libslirp0
+          wget https://github.com/cartesi/machine-emulator/releases/download/v${CARTESI_MACHINE_VERSION}/cartesi-machine-v${CARTESI_MACHINE_VERSION}_amd64.deb
+          sudo dpkg -i ./cartesi-machine-v${CARTESI_MACHINE_VERSION}_amd64.deb
+          rm ./cartesi-machine-v${CARTESI_MACHINE_VERSION}_amd64.deb
+
+      - name: Install Foundry
+        uses: foundry-rs/foundry-toolchain@v1
+
+      - name: Run devnet (Anvil)
+        run: |
+          cd rollups-node
+          make devnet
+          make run-devnet
+
+      - name: Build Node v2 image
+        run: |
+          docker build -t node_v2 -f ./ci/Dockerfile .
+
+      - name: Run Node v2 image
+        run: |
+          docker run -d --env-file ./ci/env.nodev2-local \
+            --rm --network=host \
+            --name c_node_v2 node_v2
+
+      - name: Install Echo App
+        run: |
+          docker logs --timestamps c_node_v2
+          docker exec c_node_v2 cartesi-rollups-cli app deploy -n echo-dapp -t applications/echo-dapp/ -v
+
+      - name: Send input transaction
+        run: |
+          INPUT=0xdeadbeef; \
+          INPUT_BOX_ADDRESS=0x593E5BCf894D6829Dd26D0810DA7F064406aebB6; \
+          APPLICATION_ADDRESS=0x36B9E60ACb181da458aa8870646395CD27cD0E6E; \
+          cast send \
+              --mnemonic "test test test test test test test test test test test junk" \
+              --rpc-url "http://localhost:8545" \
+              $INPUT_BOX_ADDRESS "addInput(address,bytes)(bytes32)" $APPLICATION_ADDRESS $INPUT
+
+      - name: Query Database for Output
+        run: |
+          MAX_RETRIES=30
+          for i in $(seq 1 $MAX_RETRIES); do
+            RESULT=$(docker exec -i postgres psql -U postgres -d rollupsdb -t -c "SELECT * FROM public.output;")
+            if [[ "$RESULT" =~ "deadbeef" ]]; then
+              echo "Result found: $RESULT"
+              exit 0
+            fi
+            echo "Result: $RESULT"
+            echo "Waiting for result... attempt $i"
+            sleep 5
+          done
+          echo "Timeout reached: result not found"
+          docker logs --timestamps c_espresso
+          exit 1
 
   build:
     name: Build and test
